grafana/k6build

.golangci.yml, apiserver.go, apiserver_test.go, build.go, cache.go, cache_client.go, cache_client_test.go, cache_server.go, cache_server_test.go, cache_test.go, client.go, client_test.go, cmd/client.go, cmd/cmd.go, cmd/local.go, cmd/server.go, errors.go, local.go, local_test.go, remote.go, remote_test.go, testutils.go
Implements build service and the client library.
Also introduces a cache server for serving artifact downloads
=> Implement build service

cache_server.go, cache_server_test.go
=> Fix download url

Makefile, README.md, cmd/cmd.go, go.mod, go.sum, tools/gendoc/main.go
- Add minimal usage description to the root command
- Generate README.md from cobra.Command (make readme)
=> Set missing fields in root command and generate README.md from cobra.Command

README.md, build.go, cmd/cmd.go, cmd/local/local.go, cmd/remote/remote.go
Redefine cli commans to better reflect function:
- remote: build using a remote service
- local: build localy
=> Redefine cli commands

pkg/cache/file/file.go, pkg/cache/file/file_test.go, pkg/local/local.go, pkg/local/local_test.go
=> prevent concurrent builds of same artifact

pkg/cache/server/server.go
=> fix object not found log

pkg/client/client.go, pkg/client/client_test.go
=> Add request headers

error.go, error_test.go, pkg/api/api.go, pkg/cache/api/api.go, pkg/cache/client/client.go, pkg/cache/client/client_test.go, pkg/cache/file/file.go, pkg/cache/server/server.go, pkg/client/client.go, pkg/client/client_test.go, pkg/local/local.go, pkg/server/server.go
Serialized wrapped errors to allow reconstruction when sent across API requests
=> Serialize wrapped errors

cmd/local/local.go, cmd/server/server.go, pkg/builder/builder.go, pkg/local/local.go, pkg/local/testutils.go, pkg/store/file/file.go
Refactor the local build service constructor to facilitate creating build services backed by other object stores.
=> refactor local build service

pkg/store/downloader/downloader.go, pkg/store/downloader/downloader_test.go, pkg/store/file/file.go, pkg/store/file/file_test.go, pkg/store/s3/s3.go, pkg/store/server/server.go, pkg/store/server/server_test.go, pkg/store/store.go
Refactor dowload method out of the ObjectStore interface as a utility method
=> refactor store download method

cmd/server/server.go, pkg/client/client.go
=> don't override server url path

cmd/remote/remote.go, cmd/store/store.go, pkg/client/client.go, pkg/store/client/client.go, pkg/store/client/client_test.go, pkg/store/downloader/downloader.go, pkg/store/downloader/downloader_test.go, pkg/store/server/server.go, pkg/store/server/server_test.go
=> Harden http requests

.golangci.yml, .goreleaser.yaml, pkg/builder/builder.go, pkg/builder/builder_test.go, pkg/builder/testdata/catalog.json, pkg/builder/testdata/deps/k6/cmd/k6.go, pkg/builder/testdata/deps/k6/go.mod, pkg/builder/testdata/deps/k6ext/go.mod, pkg/builder/testdata/deps/k6ext/main.go, pkg/builder/testdata/deps/k6ext2/go.mod, pkg/builder/testdata/deps/k6ext2/main.go, pkg/server/server_test.go
Mock k6foundry to simplify testing
=> Mock k6foundry

pkg/builder/builder.go, pkg/builder/metrics.go
=> add request duration metric

README.md, cmd/server/server.go
=> add liveness probe

pkg/builder/builder.go
=> return consisten version for hash builds

.github/workflows/lint.yml, .golangci.yml, pkg/builder/builder.go, pkg/builder/metrics.go, pkg/catalog/catalog.go, pkg/store/store.go
=> fix: request and build time metrics mixup

cmd/server/server.go, cmd/store/store.go
This change implements graceful shutdown support for both `k6build server` and `k6build store`
Closes: #149
=> Graceful shutdowns

go.mod, pkg/builder/builder.go
refactor builder to separate steps into different functions  to lower the complexity of the code.
=> refactor builder

go.mod, go.sum, integration/integration_test.go, pkg/builder/builder.go, pkg/store/file/file.go, pkg/store/file/file_test.go, pkg/store/file/lock.go, pkg/store/file/lock_nix.go, pkg/store/file/lock_test.go, pkg/store/file/lock_windows.go, pkg/store/s3/s3.go, pkg/store/s3/s3_test.go, pkg/store/server/server.go, pkg/store/store.go, pkg/util/download.go
Fixes https://github.com/grafana/k6build/issues/130
=> Retry object creation conflict
